### ISSUE TITLE
Is there a way you can fix the 8 direction input only with joystick?

### ISSUE THREAD

**Issue by Randy28CR** [Lyall/MetaphorFix#10]
Hi there!
The game has a problem when you play it with controller on PC: instead of 360 movement, it only moves in 8 directions, making the movement a bit choppy. It does not happen on console.
Is this something you can fix someway?
Regards!

**Comment by Lyall** [comment]
Yeah I think I can fix this. I think I found where the analog input is being gated.

Before:
https://github.com/user-attachments/assets/96641375-d1ef-4a42-9b5a-82e6d4594dc4

After:
https://github.com/user-attachments/assets/f8703718-042d-4160-993c-f6e4badf0ca3

**Comment by Randy28CR** [comment]
You are insane, man 🔥
Hope you can put it on your next patch.
Also, just for you to know, Persona 5 Strickers has this same issue. If you could address it and add it to your fix for that game ir would be much appreciated!
Thank you!

**Comment by Lyall** [comment]
> You are insane, man 🔥 Hope you can put it on your next patch. Also, just for you to know, Persona 5 Strickers has this same issue. If you could address it and add it to your fix for that game ir would be much appreciated! Thank you!

There's already a [fix for that issue](https://github.com/rebtd7/p5spc.SmoothAnalogMovement) for P5 Strikers. I could look at adding it but it doesn't make a ton of sense if someone has already done the work!

**Comment by Randy28CR** [comment]
I remember trying it out that mod like 4 months ago and I don't remember it actually work properly, not like it works in the video you have shown. 
What about if I try that mod and, if it actually does not work properly, I let you know and you add it?

**Comment by Lyall** [comment]
> I remember trying it out that mod like 4 months ago and I don't remember it actually work properly, not like it works in the video you have shown. What about if I try that mod and, if it actually does not work properly, I let you know and you add it?

Sure. It was fairly easy to track down the issue in Metaphor so I presume it would be straightforward enough in Strikers.

**Comment by Lyall** [comment]
Here is a build with the 8-way analog fix in. If you try it, let me know how it works for you and I can mark is a proper release.

https://github.com/Lyall/MetaphorFix/releases/tag/v0.7.6

**Comment by Randy28CR** [comment]
Lyall, couple of things:

1. You are awesome! The movement has been fixed and it now works as on consoles. Thank you so much! It works on both Steam and MS Store version of the game's demo.

2. Already tried that mod of P5 Strikers using Reloaded II. I made sure everything was properly set up and, unfortunately, that did not fix the 8-way analog in that game.

If you could add this same fix to your Persona 5 Strikers mod, I would deeply appreciate it!

**Comment by Lyall** [comment]
> Lyall, couple of things:
> 
> 1. You are awesome! The movement has been fixed and it now works as on consoles. Thank you so much! It works on both Steam and MS Store version of the game's demo.
> 2. Already tried that mod of P5 Strikers using Reloaded II. I made sure everything was properly set up and, unfortunately, that did not fix the 8-way analog in that game.
> 
> If you could add this same fix to your Persona 5 Strikers mod, I would deeply appreciate it!

I have added it to the latest version of P5StrikersFix if you'd like to try it out.
