### ISSUE TITLE
[Feature Request] Disable Dash Grunt

### ISSUE THREAD

**Issue by HatedUser** [Lyall/MetaphorFix#101]
https://streamable.com/tb85n9

**Comment by Randy28CR** [comment]
https://www.nexusmods.com/metaphorrefantazio/mods/12?tab=description

You might find this useful

**Comment by HatedUser** [comment]
I do find that useful. Thanks!

**Comment by HatedUser** [comment]
Nevermind. The mod is removed :(

**Comment by Foul-Tarnished** [comment]
> Nevermind. The mod is removed :(

https://gamebanana.com/sounds/76583

**Comment by HatedUser** [comment]
> https://gamebanana.com/sounds/76583
> 
> Atlus games modding scene is way more active on GameBanana.

Do you have to use the Reloaded-II MM, or is there a manual install method that I am too dumb to recognize? I am using it and added MataphorFix to Reloaded-II, but if I can go without a Mod Manager, that'd be cool.

**Comment by Lyall** [comment]
> > https://gamebanana.com/sounds/76583
> > Atlus games modding scene is way more active on GameBanana.
> 
> Do you have to use the Reloaded-II MM, or is there a manual install method that I am too dumb to recognize? I am using it and added MataphorFix to Reloaded-II, but if I can go without a Mod Manager, that'd be cool.

I'd imagine there is no manual method of using mods like those. Part of what Reloaded-II and it's mods offer is the ability to interact with and override files contained with the CriPak (CPK) archives. If launching the mod manager is what's bothering you, you could deploy the ASI loader under "Edit Application" and then whenever you launch the game your Reloaded-II mods will be loaded.

**Comment by HatedUser** [comment]
Thanks for the tip! It is nice to get rid of an extra step. At first, I couldn't find the ASI loader, but then I realized it was under Advanced Tools & Options. Thanks! And thanks to everyone else for posting the mods. It's great there is no more grunting.
