### ISSUE TITLE
[Feature Request] Keep address for old versions

### ISSUE THREAD

**Issue by Foul-Tarnished** [Lyall/MetaphorFix#102]
Could you keep the address to patch old versions ?

Sadly updating to 0.8.3 makes a few settings not work on 1.02 anymore, like 
``[2024-10-21 03:40:33.493] [MetaphorFix.log] [error] Camera Shake: Pattern scan failed.``

Sure most people should update their game, but I think it's best to have some logic to make this mod work for all versions of the game.

Sure you can revert the commit that updated the camera shake pattern and build the mod with VS

**Comment by Lyall** [comment]
I struggle to see the point of that. I can understand at least supporting the Prologue demo but I don't quite get why supporting older game versions would make sense. It sounds like quite a bit of extra work for very little gain, especially when those users could just remain on the last version of MetaphorFix that worked on that game version.
