### ISSUE TITLE
Custom shadow resolution broken on game 1.04 + fix 0.8.3

### ISSUE THREAD

**Issue by ipisano** [Lyall/MetaphorFix#103]
As title, the setting appears to be completely ignored. Too lazy to provide screenshots, but I'm 100% sure the issue is there, as the difference from stock and increased shadow resolution is **extremely** noticeable on my 4K display.  Rolling back to 0.8.2 fixed the issue. Of course, I have two separate ini files because the config names/parameters have been changed.

Unrelated, but I also either don't understand the camera sway option or that doesn't work either. I never tested it on 1.03 or before, but on 1.04 the option doesn't seem to work either on fix 0.8.2 or 0.8.3, but there's an option in the game's setting that apparently removes that sway? It does help a lot with the perceived amount of aliasing.

If that matters, I'm playing the MS Store /  Xbox / UWP / WinGDK version.

Edit: I'm using the "regular" version of the fix, not the Reloaded one.

Edit 2: Well, now I'm confused. I quit the game while writing this issue because in 0.8.2 there's no pause on focus loss, and my keystrokes were being sent to the game. Once I reopened the game, shadows were low-res. I tried swapping back and forth between 0.8.2 and 0.8.3, testing different values, but shadows are low-res. I've attached the log file, apparently the memory pattern scan fails for the camera shake but works for the shadow resolution part. I've also attached my config and the hashes of the fix's .asi , to prove I'm not going crazy

[MetaphorFix.log](https://github.com/user-attachments/files/17465261/MetaphorFix.log)
[MetaphorFix.ini.txt](https://github.com/user-attachments/files/17465300/MetaphorFix.ini.txt)
![explorer_P7c1orZQxz](https://github.com/user-attachments/assets/1fb02e5e-15bd-4ca5-93a8-c4cc6c806d82)
![ApplicationFrameHost_ULvMb7r4Ib](https://github.com/user-attachments/assets/9407df06-e401-4d8b-a19d-9863626cf3a2)

Edit 3: Tested 0.7.9, 0.8.0 and increased shadow res works. Tested 0.8.1, 0.8.2, shadows are low-res. I could've sworn I was using 0.8.2 and that was working, I don't know what to say.

**Comment by system2ckc** [comment]
The shadows tweak atleast on Steam version does work. As for the camera, for me I had to enable it in-game, and then set to true in the metaphor ini. If the in-game is set to disable, the metaphor tweak isn't working as intended.

**Comment by Lyall** [comment]
So to clarify, you're still having issues with the shadow resolution when using v0.8.3 of MetaphorFix with your MS Store version of the game?

Also, the camera shake option does not work for you and the pattern scan for that fails?

**Comment by ipisano** [comment]
> So to clarify, you're still having issues with the shadow resolution when using v0.8.3 of MetaphorFix with your MS Store version of the game?
> 
> Also, the camera shake option does not work for you and the pattern scan for that fails?

As you can see from the attached MetaphorFix.log at line 3 I'm running 0.8.3, scroll down to line 129 and you can see the pattern scan fails. And yes, I re-re-re-re-tested and confirm that shadows are broken, actually I tested with no mod at all and shadows are slightly higher resolution. The breaking point for the increased shadow resolution working with me is 0.8.1, as in the last version they work properly on is 0.8.0

At the moment I'm using 0.8.0 and I'm kind of happy with it, asides from the camera sway disabler not working but I just disabled it in the game's settings instead (I guess it disables more kind of camera movements? I don't know honestly as I've never seen your implementation).

I understand you probably don't have access to this version of the game, if I can do anything to help you get to the bottom of this let me know, asides from lending you my MS Account for security concerns.

**Comment by Lyall** [comment]
> > So to clarify, you're still having issues with the shadow resolution when using v0.8.3 of MetaphorFix with your MS Store version of the game?
> > Also, the camera shake option does not work for you and the pattern scan for that fails?
> 
> As you can see from the attached MetaphorFix.log at line 3 I'm running 0.8.3, scroll down to line 129 and you can see the pattern scan fails. And yes, I re-re-re-re-tested and confirm that shadows are broken, actually I tested with no mod at all and shadows are slightly higher resolution. The breaking point for the increased shadow resolution working with me is 0.8.1, as in the last version they work properly on is 0.8.0
> 
> At the moment I'm using 0.8.0 and I'm kind of happy with it, asides from the camera sway disabler not working but I just disabled it in the game's settings instead (I guess it disables more kind of camera movements? I don't know honestly as I've never seen your implementation).
> 
> I understand you probably don't have access to this version of the game, if I can do anything to help you get to the bottom of this let me know, asides from lending you my MS Account for security concerns.

I'm curious as to why the shadow resolution wouldn't be working for you as it appears to be detected and modifying the correct area of code (though I need to clarify that with access to the game exe). Are you using SpecialK with this game? 

You don't need to share account details or anything. Just uploading the game exe will let me compare patterns and such which should be enough. Obviously I can't test the changes on an exe but I could generate a test build and then you could test it and report back. 

So to dump the exe for the MS Store version, you'll need to use [UWPDumper](https://github.com/Wunkolo/UWPDumper/releases/download/latest/UWPDumper.zip). You just launch the game, then launch the x64 version of UWPInjector.exe, type the process ID and it'll spit out unencrypted dumped game files. You would then upload the shipping executable for P3R (in `P3R\Binaries\WinGDK`) to somewhere like [Pixeldrain](https://pixeldrain.com/) or whatever file host you prefer.

**Comment by ipisano** [comment]
[There you go](https://gofile.io/d/AGEGi5), sorry for the rar, actually had to go and download it myself because 7zip kept getting to 99% instantly and then being stuck there for minutes. The password is "shadowsplz" without quotation marks. Let me know if you need anything else.

Oh and since you asked I don't use SpecialK, I do use the latest ReShade with addons support. I didn't mention it as I've already tested with it disabled (.dll renamed) and excluded it being the culprit.

**Comment by Lyall** [comment]
Thanks for posting that and sorry for not getting to it sooner. In v0.8.4, I've moved the graphics hooks/patches to apply earlier, this may fix the shadow issue for you as the patterns all match and the code seems roughly the same.

As for the camera shake, they actually just patched the game today and it looks like the reverted some of the changes they made in the last patch. It's possible it's just a different compiler output but regardless, v0.8.4 might work on the latest MS Store version now that the pattern is similar to the way it used to be. 

If you try that version, let me know how it goes and post a log file.

**Comment by ipisano** [comment]
With the latest version of the game (which apparently is called 1.09?) running the latest version of your fix everything works perfectly, great job! I still don't understand what the difference between disabling the camera shake in the fix .ini is compared to doing it in-game, but shadows have increased resolution, and with the in-game camera shake set to on while having it disabled in the fix .ini I don't get the idle swaying, so I guess it's working as intended. I'm gonna close this issue, but I'm still curious about the camera thing.

**Comment by Lyall** [comment]
> With the latest version of the game (which apparently is called 1.09?) running the latest version of your fix everything works perfectly, great job! I still don't understand what the difference between disabling the camera shake in the fix .ini is compared to doing it in-game, but shadows have increased resolution, and with the in-game camera shake set to on while having it disabled in the fix .ini I don't get the idle swaying, so I guess it's working as intended. I'm gonna close this issue, but I'm still curious about the camera thing.

Glad to hear it's working for you now! The main difference with the camera shake option in MetaphorFix is that it disables camera shake/sway everywhere, not just when running about and in dialogues as the in-game option does. Think of it like a global off switch for the camera shake/sway instead of it being selectively disabled when using the in-game option.
