### ISSUE TITLE
[Stupid Question] To revert game back to normal unmodded state, do I only need to delete the extracted files and nothing else? or are there any settings that get saved or baked into a save file or something?

### ISSUE THREAD

**Issue by KeruKiru** [Lyall/MetaphorFix#106]
I know this is a really stupid question, but to completely revert settings to normal I only need to delete the 4 extracted files?
The .asi .ini .md and the .dll
None of the modded settings are saved or baked into the game files or anything (like skyrim for example)?
The changes I made a really subtle, so I can't tell if they're really gone or not.
Thanks for taking the time to reply to this imbecile (me).

**Comment by MYSTICALMUSICAL** [comment]
Yes, you only have to delete those files. 
This mod works as a sort of injector: without all files present, nothing will load (with the exception of the .md file, that one is basically a "readme" file and isn't required the other three files). No changes are baked into the executable itself.
