### ISSUE TITLE
HUD! Centered, does not stretch properly

### ISSUE THREAD

**Issue by ghost** [Lyall/MetaphorFix#109]
Both the game menu and the HUD during battles remain centered and do not adapt to my 32:9 screen. I have applied patch 0.8.4 and 0.7.9, both have the same effect. Is there a solution?
![IMG_6588](https://github.com/user-attachments/assets/448748c7-3314-4f5f-ac2d-ecd0d6ca0939)
![IMG_6589](https://github.com/user-attachments/assets/57599168-f7a1-4911-a11e-3048e330029c)
![IMG_6586](https://github.com/user-attachments/assets/ce47a28b-843a-496b-90b5-73b4778fe6d4)
![IMG_6587](https://github.com/user-attachments/assets/0c6e6b8a-d88c-47a0-bfaa-3770fd81a8c0)
![IMG_6590](https://github.com/user-attachments/assets/1e9b2311-8015-4f76-875c-8d58d776b6c9)

**Comment by Lyall** [comment]
That's expected behaviour, if you want the HUD to be stretched then disable the "[Fix HUD]" feature in `MetaphorFix.ini`.

**Comment by Pumukki95** [comment]
I was referring more to the combat one. “dark overlay”

**Comment by Lyall** [comment]
Yeah HUD spanning is not going to be happen, at least not without many, many hours of work.
