### ISSUE TITLE
[Bug] Most recent patch broke the camera shake disable

### ISSUE THREAD

**Issue by solidsoap23** [Lyall/MetaphorFix#112]
Me again :) I reported this the last time it happened... seems that the most recent patch broke the camera shake fix again.

**Comment by dclock** [comment]
Might also be worth noting that the new patch also adds an option to remove motion blur on dash, so that feature of MetaphorFix might be obsolete now.

**Comment by MYSTICALMUSICAL** [comment]
> Might also be worth noting that the new patch also adds an option to remove motion blur on dash, so that feature of MetaphorFix might be obsolete now.

The new patch option does indeed remove both motion blur and the speed lines effect.
I wonder if Lyall could transform that feature into keeping the speed lines visible, but still keeping motion blur disabled.
I just think it's a cool effect, but it would suck if the speed lines were somehow tied to the motion blur post-processing.

**Comment by Lyall** [comment]
I have fixed this in v0.8.4. Also the "Disable Dash Blur" option has been removed. I did look at separating the radial blur and the speed lines but I had no such luck sadly. I don't think it's a coincidence that the effect is disabled in a similar way to how MetaphorFix did it.

**Comment by Randy28CR** [comment]
> I have fixed this in v0.8.4. Also the "Disable Dash Blur" option has been removed. I did look at separating the radial blur and the speed lines but I had no such luck sadly. I don't think it's a coincidence that the effect is disabled in a similar way to how MetaphorFix did it.

Do you have good news on fixing the Bloom?
I saw you were looking for that as well 🤞🏼

**Comment by Lyall** [comment]
> Do you have good news on fixing the Bloom? I saw you were looking for that as well 🤞🏼

No luck on the bloom so far. I haven't found a way to get it to match the look of the PS5 version yet. If I do get anywhere, I'll post an update in that issue thread.

**Comment by Randy28CR** [comment]
> > Do you have good news on fixing the Bloom? I saw you were looking for that as well 🤞🏼
> 
> No luck on the bloom so far. I haven't found a way to get it to match the look of the PS5 version yet. If I do get anywhere, I'll post an update in that issue thread.

Thank you so much for you efforts, mate. I think this bloom stuff is like the final boss in order for this game to have the quality it should have been in the first place (well, fix the AA is def not reachable).
If you need any support of some kind to achieve it let us know in that issue thread!
