### ISSUE TITLE
Documenting issues with WIP "Fix HUD"

### ISSUE THREAD

**Issue by kstll** [Lyall/MetaphorFix#14]
I know this setting is a work in progress and you're probably aware of these issues, but wanted to capture the problems I'm currently seeing when enabling "Fix HUD" on an ultrawide (3440x1440) monitor. Thanks very much for your work on this improvement.

1. The minimap is greyed out & objective marker seems to be displayed in incorrect locations
2. HP / MP bars are a static image / don't change to reflect damage
3. Under certain circumstances (seems to happen when entering / exiting settings menu after making resolution changes), the main menu "selection" bar will be misaligned with the menu options

![2024-10-07 15_57_34-Metaphor_ ReFantazio - Prologue Demo](https://github.com/user-attachments/assets/7cbc7190-4e4d-4bcb-aded-ffd047b76b06)

**Comment by Lyall** [comment]
The WIP HUD fix has been removed as of v0.7.7

**Comment by stefanoriva-xs** [comment]
any chance that the hud fix will be introduced in later patches or the way the game handles it is too tricky to get it to work properly? anyway, thanks for all of this, i'll keep supporting

**Comment by Lyall** [comment]
> any chance that the hud fix will be introduced in later patches or the way the game handles it is too tricky to get it to work properly? anyway, thanks for all of this, i'll keep supporting

I'd like to yeah, but everything I've tried so far has been imperfect. The way they do the UI in this game is very complicated as you might imagine given it's stylization. I've mainly just removed the HUD fix for now as I've put many, many hours into coming up with a solution and none have been ideal. Not writing off a potential HUD fix in the future but for now, it's not on the cards.

**Comment by stefanoriva-xs** [comment]
i figured as much, i hope that with the full release of the game, being able to view and see the individual files might help to find a work around since the demo version had only one packaged file, thank you again

**Comment by kstll** [comment]
Sorry to hear. For what it's worth, even with the bugs I really, really preferred having this setting on, losing minimap was a small price compared to stretching out all the art and menus.
