### ISSUE TITLE
Camera shake in dialogue

### ISSUE THREAD

**Issue by JamesPond007** [Lyall/MetaphorFix#15]
The camera sway during dialogue is wild. I was hoping it's possible for you to patch this in the mod? 

It's really making me quite quasy and I usually never encounter this in SMT or Persona games. 

If not possible, thank you for all your hard work regardless. You are a legend.

**Comment by JamesPond007** [comment]
> i think this is a normal setting in the game tho, it's called Camera Shake, try disabling it

Its more like a camera sway, it's only in dialogue. I'll try to record it.

**Comment by stefanoriva-xs** [comment]
i know what you mean, i noticed it too but it doesn't really bother me, it adds somethin more when dialogues run. If Camera Shake setting does not remove it in dialogues, i don't know what else could it be referencing at this point

**Comment by MakoEyes** [comment]
Hey, I actually just made another post about this. The in-game setting for camera shake does nothing for actual story sequences. It continues to sway. It is horrendous and distracting. I was also hoping there would be a fix for it. Have seen other complaints about the same thing on forums.

**Comment by Lyall** [comment]
I have added this option in this test build. Check `MetaphorFix.ini` to enable it. 
[MetaphorFix_v0.8.0_test3.zip](https://github.com/user-attachments/files/17354937/MetaphorFix_v0.8.0_test3.zip)

I've only done some very quick testing on this so feedback would be helpful.

**Comment by JamesPond007** [comment]
That is awesome, thank you so much man!! @Lyall 

I'm gonna test it in a bit!

**Comment by MakoEyes** [comment]
> I have added this option in this test build. Check `MetaphorFix.ini` to enable it. [MetaphorFix_v0.8.0_test3.zip](https://github.com/user-attachments/files/17354937/MetaphorFix_v0.8.0_test3.zip)
> 
> I've only done some very quick testing on this so feedback would be helpful.
> 
> Edit: In my testing the most obvious bug is that it will force camera shake off even outside of dialog. It's effectively changing the same setting. Though I imagine that most people who dislike the camera sway in dialog will want camera shake off anyway so 🤷

Lyall, as somebody who suffers from chronic vertigo, thank you so much! I will test it later tonight and get back to you. Will be throwing a donation on your patreon. Appreciate the time and effort to make this experience better for all.

**Comment by system2ckc** [comment]
Seems to also effect combat as well. Not a big deal though, unsure if I'll use this myself yet. It does help with minimizing aliasing when camera is still but the scenes lose some dynamic feel to them.

**Comment by MakoEyes** [comment]
@Lyall 

I tested it out. It works beautifully during cutscenes. As you stated, it definitely turns off screen shake everywhere, but you are correct in that I think many of us wanted it off period (or atleast that is my preference). It now does what I wished the in-game setting did, which is to disable screen shake in all instances. Thanks again.

**Comment by Lyall** [comment]
This has been added in v0.8.0.
