### ISSUE TITLE
fov keep increasing after each fight

### ISSUE THREAD

**Issue by pair12** [Lyall/MetaphorFix#18]
hello,

first thank you for this fix, it's awesome.

i have an issue, every time i go in the fight mode, when the game exit and go the exploring mode, fov increases by itself, after 2 or 3 fights the fov is way too high, way higher than i set it in MetaphorFix.ini, i have set it at 1.3.

i have all options at default in this ini, i tried setting things to false in the section Ultrawide/Narrower Fixes, but that didnt fix the issue.

you are aware of this issue ?

**Comment by pair12** [comment]
i see you just removed fov from description, does it mean fov tweaking wont be available for this game ?

**Comment by Lyall** [comment]
> i see you just removed fov from description, does it mean fov tweaking wont be available for this game ?

For now yes. Tracking down where the gameplay FOV is actually being set is proving remarkably tricky. I will revisit this at a later date but for now the feature is removed.

**Comment by pair12** [comment]
ok, thank you for answering me on this :)
i hope it can come back in the future, default game fov is so low :(
