### ISSUE TITLE
Ultrawide not working properly

### ISSUE THREAD

**Issue by Nimda69** [Lyall/MetaphorFix#20]
I cannot seem to get this mod to be working.

Way it works for me now is :
When i set my resolution to 2560 x 1440 it will be ultrawide but very stretched.
When i set my resolution to 3440 x 1440 it turns back to 16:9 ratio and no ultrawide.

Tried fullscreen and borderless.
I've played around with the various settings in the  "fix" file. But nothing seems to do the trick.

Hopefully you can help me.

**Comment by Lyall** [comment]
Please post your MetaphorFix.log file.

**Comment by Nimda69** [comment]
> Please post your MetaphorFix.log file.

I've done a complete reinstall of the game(demo), and that seemed to fix it!
Thanks anyways for the reply. I'm hoping this will also be working for the full version. 
Seems to be a very cool game.
