### ISSUE TITLE
Is it possible to fix low sound via mod?

### ISSUE THREAD

**Issue by Randy28CR** [Lyall/MetaphorFix#22]
It´s me again hehe
I find sound in this game extremely low, even master sound maxed out. I tried things like FxSound or Voicemeeter Banana but they do not have a per process option, using them for that purpose is useless as unbalanced audio remain that way, just louder overall.
Is there a way to increase sound values beyond the ones found in the game by modding them?

Regards mate!

**Comment by PhiZero** [comment]
I'd like to put my dime in the hat for this one. The audio in this game is far lower than anything else. Would be extremely appreciated if there's some way to get a higher max master volume.

**Comment by Lyall** [comment]
I've added an override for the master volume value. I'm not sure if it'll cause issues or not. I tried cranking it up to 10 in testing and it didn't distort or blow out so I assume there's some kind of actual limit later on in the chain. For this option I've limited it to a max of 4 though just in case. For reference the master volume slider in-game ranges from 0 to 1.00, so you can now go all the way up to 4.00 with the override. Just set it in `MetaphorFix.ini` and it'll override the master volume value.

[MetaphorFix_v0.8.0_test.zip](https://github.com/user-attachments/files/17349566/MetaphorFix_v0.8.0_test.zip)

**Comment by Randy28CR** [comment]
Volume level completely fixed.
Lyall has done it again!

I would like to take the opportunity to give visibility too to these issues: 

-Camera shake (sway) not completely disabled by the option in the menú: https://github.com/Lyall/MetaphorFix/issues/15
https://github.com/Lyall/MetaphorFix/issues/26

-Disable dialogue box animation:
https://github.com/Lyall/MetaphorFix/issues/19
https://github.com/Lyall/MetaphorFix/issues/42

I deeply appreciate your work. You have enhanced the experience in this game and in many others for many of us.
I will donate you in my next payment, and most likely I will still owe you money!
Thank you so much, legend!

**Comment by PhiZero** [comment]
Works like a charm here too. Thank you so much!

**Comment by Lyall** [comment]
This has been added in v0.8.0.
