### ISSUE TITLE
using sprint fix the fov issue

### ISSUE THREAD

**Issue by pair12** [Lyall/MetaphorFix#24]
hello,

i've been using 7.6 this morning with fov set to 1.5 and i noticed that when you use sprint, the fov reset to set value, this "fixes" the fov going higher and higher fight after fight.

could you please put back fov into your fix ? i think this is a nice workaround for now.

thank you and sorry for putting this into new issue but the one (issue 18)  is closed now.

**Comment by Lyall** [comment]
I've reworked the gameplay FOV stuff in this test build if you'd like to give it a try. I tested out several cutscenes and some combat and it doesn't seem to break on my end, but I'm not very far in the game so testing would be helpful.

[MetaphorFix_v0.7.8_test.zip](https://github.com/user-attachments/files/17326432/MetaphorFix_v0.7.8_test.zip)

**Comment by pair12** [comment]
just tested your test build, and it's still happening for me, i do not know why it's fine for you, and i also do not understand why noone else have reported this fov issue, maybe it's my side for some reason.

anyway with the sprint workaround it's perfectly playable, specially since once activated it stays that way even when leaving combat and thus fov is reseted.

**Comment by Lyall** [comment]
I was 100% able to reproduce the issue you mentioned before, where the FOV would continue to increase after loading or combat etc..

I haven't been able to do a lot of testing with this new build, hence me posting it to get your feedback. If it's causing the same issue again, I'll take another approach and come back with another test build for you to try.

**Comment by pair12** [comment]
ok :)

looking forward for it :) thank you for working on this !

**Comment by nicolasgustafsson** [comment]
Can confirm it still happens on this build - specifically when going out of the combat scene into the exploration scene(I've found no other repro). Still using it cause the sprint fixes it and I get motion sick with the default fov hehe

**Comment by pair12** [comment]
i hope fov keeps getting added to future versions cause yes using sprint fixes this issue, and it's perfectly playable that way.

**Comment by Lyall** [comment]
Alright I have another test build you can try with FOV adjustment added back in. The game uses this single function to set FOV in many different places so I've added a condition to check if it's adding back on itself.

[MetaphorFix_v0.8.0_test4.zip](https://github.com/user-attachments/files/17356281/MetaphorFix_v0.8.0_test4.zip)

**Comment by Lyall** [comment]
In my own testing this seems to work. So I've added it back in v0.8.0. Fingers crossed there aren't any issues with it!

**Comment by nicolasgustafsson** [comment]
> In my own testing this seems to work. So I've added it back in v0.8.0. Fingers crossed there aren't any issues with it!

I've had no issues so far either, but I haven't been in many combats yet! I'll write here if I find any

**Comment by pair12** [comment]
i'm not in a place i can fight, but tomorrow morning i will test this, already installed, will report back :)

**Comment by pair12** [comment]
happy to report, your fix fov indeed works great now, amazing, thank you so much for the whole fix, so many amazing features :)

**Comment by nicolasgustafsson** [comment]
I've noticed one case in which FOV can still infinitely scale. If you stun an enemy in the overworld repeatedly without going into combat, it will not reset until you sprint.
