### ISSUE TITLE
Ultrawide HUD fix is nearly there in v0.7.6!

### ISSUE THREAD

**Issue by Khrisoo** [Lyall/MetaphorFix#28]
Hey Lyall, thanks for working on this fix. I've been playing with v0.7.6 and its WIP HUD fix enabled, and the fix is very close to fixing all the stretched elements. I note you have removed this feature for now, but I believe you are close and note that you have shared more HUD findings in another recent thread.

The stretched elements that aren't fixed yet are:
-End-of-day transition FMV
-Going into Akademia FMV
-Transition cutscene between parts of city FMV
-Portrait animation during combat start FMV
-HP/MP bars not reflecting correct values for both party and enemies - always showing as full (can check enemy health by "Analyse" however)
-Mini-map basically non-functional and character location not correct on full map
-Calendar selection windows misaligned
-Archetype selection windows misaligned
-Diamond markers in Quest screen misaligned

Tested on a 3840x1600 monitor.

**Comment by liunice** [comment]
Wow, these are really helpful. But why did he remove WIP HUD fix?

**Comment by decafcoffee-yu** [comment]
I hope the stretched-out elements can be fixed as a priority. They affect how people experience the game most straightforwardly.

**Comment by Khrisoo** [comment]
I'm looking forward to seeing these last tidbits fixed up too. It's certainly a greater effort than the flawless widescreen "fix" for P5R on PC where the stretched HUD was never fixed.

liunice, Lyall has commented in this closed thread they're re-approaching the HUD fix and have removed it from the fix for now https://github.com/Lyall/MetaphorFix/issues/21. Sounds like they'll include it again once the HUD fix is more stable.

**Comment by Lyall** [comment]
New version of the HUD fix is out in v0.7.8
