### ISSUE TITLE
Models invisible in preview screens v0.7.8

### ISSUE THREAD

**Issue by Hadi10000** [Lyall/MetaphorFix#29]
example: https://prnt.sc/DCOiUOYXQdLz
The archetypes in the preview screen also have this issue.

ps: you're doing awesome work for ultrawide gaming thanks alot!

**Comment by malkilthewizard** [comment]
Noticed this as well, but I'm not playing in ultrawide. 2560x1440.

**Comment by WaffleCheesebread** [comment]
I also get this, also not ultrawide. Playing in 4k. can't see archetypes or enemy models on analysis screen.

**Comment by WaffleCheesebread** [comment]
Update: Setting all the resolution fixing things to False makes them appear just fine. Seems to be an issue if you use these settings for non-16:9 resolutions while playing with a 16:9 resolution.

**Comment by Lyall** [comment]
This should be fixed in v0.7.9. Part of the HUD fix was causing issues and it was also being enabled even at 16:9.
