### ISSUE TITLE
Game uses lower resolution assets at resolution below 4k

### ISSUE THREAD

**Issue by SandeMC** [Lyall/MetaphorFix#3]
Title explains it

There's already a fix in Essentials actually, but I don't really want to use Reloaded for just Essentials:
https://github.com/DeathChaos25/p5rpc.modloader/commit/cb7b3ee32c16a9e5d05bbae7b49aea7d24ea5187

**Comment by Lyall** [comment]
The "Texture Quality" setting in-game controls this. Is there a scenario in which that in-game setting does not work? 

![image](https://github.com/user-attachments/assets/84b60621-66ea-4e89-814a-bc9b933056cd)

**Comment by SandeMC** [comment]
Honestly not sure - from what somebody told me, the "4k assets" are higher quality and only available on 4k monitors

**Comment by Lyall** [comment]
So having looked closer at this in the full game, the option called "Texture Quality" does still indeed control this so I don't think a force option is needed. You can set this to "high" regardless of resolution so I'm unsure of any situation in which it would revert back to "Normal". If any information changes or people discover something about it, I'd be happy to add it as an option but for now I'm going to close this issue.

**Comment by SandeMC** [comment]
> So having looked closer at this in the full game, the option called "Texture Quality" does still indeed control this so I don't think a force option is needed. You can set this to "high" regardless of resolution so I'm unsure of any situation in which it would revert back to "Normal". If any information changes or people discover something about it, I'd be happy to add it as an option but for now I'm going to close this issue.

Just a question, but have you looked at what the Essentials mod is changing || what is that address responsible for?

**Comment by Lyall** [comment]
> > So having looked closer at this in the full game, the option called "Texture Quality" does still indeed control this so I don't think a force option is needed. You can set this to "high" regardless of resolution so I'm unsure of any situation in which it would revert back to "Normal". If any information changes or people discover something about it, I'd be happy to add it as an option but for now I'm going to close this issue.
> 
> Just a question, but have you looked at what the Essentials mod is changing || what is that address responsible for?

Yes, it's changing part of the game code that executes when the texture quality setting is changed. So that it forces the "high" setting. So as I said, unless there is a bug that I haven't seen that revert that setting then I don't think overriding it is necessary.

**Comment by SandeMC** [comment]
Alright then
