### ISSUE TITLE
Costume BGM Not Working

### ISSUE THREAD

**Issue by Lucifim** [Lyall/MetaphorFix#34]
When I installed this mod, the bgm for the costumes stopped working. No matter what costume I put on the characters, it always plays the default battle theme. The end of battle music does change still based on costume.

**Comment by Grendel-Zolga** [comment]
Are you sure it's the mod that's an issue? The game either way seems to only apply BGM to the "Advantage" Battle theme and leaves standard and ambushed as the default

**Comment by Lucifim** [comment]
oh. im sorry then i thought i did get advantage but ill double check again.
thank you

**Comment by Lyall** [comment]
This doesn't seem like anything that would be caused by MetaphorFix. It doesn't touch anything related to save data or DLC.

**Comment by Lucifim** [comment]
Yeah i tested again, it was just the advantage thing you said. sorry for
wasting your time
