### ISSUE TITLE
Invisible Models in Grand Cathedral Central Plaza

### ISSUE THREAD

**Issue by ALHughes466** [Lyall/MetaphorFix#35]
Playing at 1440p, 16:9 aspect ratio, default .ini settings on mod version 0.7.8. Playing the full game.
How it looks with the mod on:
![image](https://github.com/user-attachments/assets/dc8e456e-6b8b-47c2-bad0-a8cb9bdfee38)
How it should look:
![image](https://github.com/user-attachments/assets/3d5412e0-abca-419a-8865-cc1c0b73fafe)
This area is using a fixed camera. The FOV is much wider with the mod enabled, causing LOD issues, if I had to guess.
Cranking the LOD to 100 in the .ini made no apparent difference.

**Comment by ALHughes466** [comment]
I'm also seeing models disappear during in-engine cutscenes. A little further into the game, there's a cutscene where the party gets ambushed, but the attacker pops in and out of frame depending on the camera's position and the model's proximity to the camera.

**Comment by Lyall** [comment]
Should be fixed in v0.7.9

**Comment by misterwiggle** [comment]
mine has invisible character and archetype sometimes in menu or cutscene

**Comment by willcheat** [comment]
Had this issue in the 2nd city dungeon. Can confirm it is fixed with 0.79

![Untitled](https://github.com/user-attachments/assets/9f9d47d9-243c-40a1-8ca7-4cfaf43f0eab)

**Comment by ALHughes466** [comment]
Can confirm as well, appears to be fixed for me on both PC and Steam Deck.
