### ISSUE TITLE
No changes after editing MetaphorFix.ini

### ISSUE THREAD

**Issue by eldonh** [Lyall/MetaphorFix#37]
I've tried a few value changes, but no changes appear in-game. Mostly I want to disable sprinting motion blur, since it makes me genuinely motion sick. I tried with all files loose in the main game folder, as well as trying with all files in the MetaphorFix-master subfolder it extracts to by default. I've attached my MetaphorFix.ini in case I'm making some really obvious mistake here (I copied it to .txt just to upload it here, but my file is still the proper .ini extension in the game folder). Thank you to anyone that can help!
[MetaphorFix.txt](https://github.com/user-attachments/files/17347434/MetaphorFix.txt)

**Comment by Brooksiebear19** [comment]
The .ini file itself appears to be setup as it should, your ini works fine. Do all your other changes work fine? Like Intro Skip and Ultrawide fixes? I only have a 16:9 display so it could be an Ultrawide issue.

**Comment by Lyall** [comment]
> I've tried a few value changes, but no changes appear in-game. Mostly I want to disable sprinting motion blur, since it makes me genuinely motion sick. I tried with all files loose in the main game folder, as well as trying with all files in the MetaphorFix-master subfolder it extracts to by default. I've attached my MetaphorFix.ini in case I'm making some really obvious mistake here (I copied it to .txt just to upload it here, but my file is still the proper .ini extension in the game folder). Thank you to anyone that can help! [MetaphorFix.txt](https://github.com/user-attachments/files/17347434/MetaphorFix.txt)

You need to download a release build, not the source code. Go to [this page](https://github.com/Lyall/MetaphorFix/releases) and click on the latest release zip to download it.

![image](https://github.com/user-attachments/assets/ffefee6e-35c8-490f-b058-0d9cd147b0aa)

**Comment by eldonh** [comment]
I believe I had a release build already, but after removing everything and re-extracting the most recent build that was published everything is now working perfectly. So I'm guessing I just messed something up the first time. Thank you for your help!
