### ISSUE TITLE
Models dissapearing and everthing black when in combat (Kreigant Castle)

### ISSUE THREAD

**Issue by Abanthi** [Lyall/MetaphorFix#38]
Entire scene is black when you get into battle in Kriegante Castle. Removing the fix, fixed the problem. didnt change any options in the .ini except for remove dash blur. Thanks for what you do!

**Comment by Lyall** [comment]
Should be fixed in v0.7.9 if you want to give it a try.

**Comment by Abanthi** [comment]
works great!
