### ISSUE TITLE
MetaphorFix and Reloaded-II

### ISSUE THREAD

**Issue by Aikerin** [Lyall/MetaphorFix#39]
Hello Lyall,

As I'm sure you've guessed, similar to P3RFix, MetaphorFix has some problems with Reloaded-II. Is there a way to make ASI Loader load a different .dll for MetaphorFix? If not, is there a way for you to make this an R2 mod sometime soon? Metaphor Essentials has already made its way onto Reloaded-II, so the problem will crop up eventually as more people have the same problem.

Thanks

**Comment by Lyall** [comment]
Sure, I can add a Reloaded-II workflow for the next release build.

**Comment by Lyall** [comment]
Added in v0.8.0.
