### ISSUE TITLE
Game randomly refuses to go back to gamepad icons after an alt tab

### ISSUE THREAD

**Issue by SandeMC** [Lyall/MetaphorFix#4]
![image](https://github.com/user-attachments/assets/f84b9831-59e3-45c0-ac51-5232943fbd79)
I'd occasionally have to alt-tab again to get the game to show gamepad icons. 
Would an option to force gamepad icons be possible?

**Comment by Lyall** [comment]
Is this happening with `PauseOnFocusLoss` set to false in MetaphorFix.ini?

**Comment by SandeMC** [comment]
@Lyall Yeah I had that set to false when I was playing

**Comment by Lyall** [comment]
> @Lyall Yeah I had that set to false when I was playing

Did it happen before with pause on focus loss left enabled? I've just removed this option in the latest update as it was causing some bugs. I plan on revisiting it from a different approach at a later date.

**Comment by SandeMC** [comment]
I hadn't checked

**Comment by agincel** [comment]
The full game still seems to have this issue. I'd love if it were possible to just have an option to always force gamepad controls, and never show keyboard controls...

**Comment by agincel** [comment]
@Lyall I write this as I alt+f4 the game for the fifth time to reset the icons - the next 80 hours of my life would be super indebted to you if there was a way to get the game to force always having the gamepad icons shown... 😅

**Comment by Lyall** [comment]
> @Lyall I write this as I alt+f4 the game for the fifth time to reset the icons - the next 80 hours of my life would be super indebted to you if there was a way to get the game to force always having the gamepad icons shown... 😅

Is this an issue with the game even without MetaphorFix installed? I had assumed it would be related to the pause on focus loss option but I removed that several versions ago. If it does happen with the vanilla game, I can certainly look into forcing gamepad icons.

**Comment by agincel** [comment]
> > @Lyall I write this as I alt+f4 the game for the fifth time to reset the icons - the next 80 hours of my life would be super indebted to you if there was a way to get the game to force always having the gamepad icons shown... 😅
> 
> Is this an issue with the game even without MetaphorFix installed? I had assumed it would be related to the pause on focus loss option but I removed that several versions ago. If it does happen with the vanilla game, I can certainly look into forcing gamepad icons.

This is absolutely an issue with the vanilla game. For me if I _ever_ Alt-Tab out of the game while playing, keyboard icons are forced on until a full restart. It's even happened to me without an Alt-Tab, but the issue is tough to pin down. I played the first 10 hours of the game without MetaphorFix, had the issue, had someone recommend the Fix, but saw no change in behavior.

I'm sure there are more subtle system-level things (multiple controllers plugged in, type of controller) at play here causing this issue to happen for some folks but not others...I've tried running the game with Steam Input disabled and enabled but seen no difference.

**Comment by Lyall** [comment]
> > > @Lyall I write this as I alt+f4 the game for the fifth time to reset the icons - the next 80 hours of my life would be super indebted to you if there was a way to get the game to force always having the gamepad icons shown... 😅
> > 
> > 
> > Is this an issue with the game even without MetaphorFix installed? I had assumed it would be related to the pause on focus loss option but I removed that several versions ago. If it does happen with the vanilla game, I can certainly look into forcing gamepad icons.
> 
> This is absolutely an issue with the vanilla game. For me if I _ever_ Alt-Tab out of the game while playing, keyboard icons are forced on until a full restart. It's even happened to me without an Alt-Tab, but the issue is tough to pin down. I played the first 10 hours of the game without MetaphorFix, had the issue, had someone recommend the Fix, but saw no change in behavior.
> 
> I'm sure there are more subtle system-level things (multiple controllers plugged in, type of controller) at play here causing this issue to happen for some folks but not others...I've tried running the game with Steam Input disabled and enabled but seen no difference.

Okay, I just wanted to clarify that it wasn't MetaphorFix that was breaking something, since it would be better that I fix that instead! I'll look into forcing gamepad icons and report back when I have something.

**Comment by Lyall** [comment]
Okay here is a test build that has an option to force controller icons at all times. Check `MetaphorFix.ini` to enable it. 

[MetaphorFix_v0.8.0_test2.zip](https://github.com/user-attachments/files/17354795/MetaphorFix_v0.8.0_test2.zip)

**Comment by SandeMC** [comment]
FYI you can edit comments on github

**Comment by Lyall** [comment]
> I tried this as had the same issue, it fixes the issue and buttons stay after alt-tab at the sacrifice of keyboard labels and mouse itself never appearing so navigating with the mouse becomes very hard (and the volume set to 4.0 also puts the game to the proper standard full level!) but it introduces a new bug as the text labels on the in game menu are now blank, tested by switching back to old version and back again and same issue re-occurs. Note that it happens with this version regardless if the gamepad icon setting is true or false. ![1](https://private-user-images.githubusercontent.com/155030647/376026317-17d23b27-3c8e-4e2f-95e5-4726cb89543a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MTUyODUsIm5iZiI6MTcyODgxNDk4NSwicGF0aCI6Ii8xNTUwMzA2NDcvMzc2MDI2MzE3LTE3ZDIzYjI3LTNjOGUtNGUyZi05NWU1LTQ3MjZjYjg5NTQzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QxMDIzMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wODY3NjgyYWJkODc1MDc4MzBkMjJjMTdlZGNjYzQ4YmRkYWQ3YTIyZWZlNWUwMjkzZjU5ODk5NTFkMTM1OTc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9Qfmd2SE6w54xDp4v_alWFukh3PoigFLZdHE6V2wC_s)

Thanks for testing it. So you'd want ideally for the controller labels/glyphs to stay but the mouse cursor to still be visible when you switch inputs? 

The blank menu bug is unrelated, I'd been doing some testing on fixing that particular issue a different way and those changes are present in the test build.

**Comment by SandeMC** [comment]
Yeah that'd be good imo (though I'm fine with keyboard input disabled in entirety personally)

Ideally, it'd be great if you manage to fix the handler in entirety so it works automatically as intended, but I'll be fine with just forcing myself

**Comment by Lyall** [comment]
> Yeah that'd be good imo (though I'm fine with keyboard input disabled in entirety personally)
> 
> Ideally, it'd be great if you manage to fix the handler in entirety so it works automatically as intended, but I'll be fine with just forcing myself

I think fixing the root cause would be very hard given that I can't replicate the issue on my end. We'd probably have to hope for Atlus to fix it, which, given that they actually patched the demo multiple times, might happen.

**Comment by Lyall** [comment]
Here's another test build then. This time the approach is more targeted and should allow the mouse cursor to become visible.

[MetaphorFix_v0.8.0_test4.zip](https://github.com/user-attachments/files/17356293/MetaphorFix_v0.8.0_test4.zip)

**Comment by agincel** [comment]
It works great!!!

**Comment by Lyall** [comment]
Thanks for the feedback! This is added in v0.8.0.
