### ISSUE TITLE
Bug in close the game

### ISSUE THREAD

**Issue by Brenndo-l** [Lyall/MetaphorFix#40]
Hello good evening, a bug is occurring when you try to close the game either with alt+f4 or by the standard method where the window also closes the game but it continues to run and your music continues to play in the background and you have to stop it via Steam or the task manager.

**Comment by Lyall** [comment]
Hmm, can't say I've encountered this bug throughout any of my testing. Are you using any overlays or software that might inject into the game?

**Comment by Kingsern** [comment]
i have the same issue, it might be caused by special k since it started after i installed it

**Comment by Brenndo-l** [comment]
> Hmm, can't say I've encountered this bug throughout any of my testing. Are you using any overlays or software that might inject into the game?

Yes, I use Special K, without it my game is very poorly optimized, I didn't think it would cause this problem along with the fix

**Comment by system2ckc** [comment]
When I don't run specialK this issue doesn't occur.

**Comment by Lyall** [comment]
> When I don't run specialK this issue doesn't occur.

It's probably related to the fact that both MetaphorFix and SepcialK will set a new WndProc and have some feature overlap. I can add an option to control this in the next version. Then you could disable it in `MetaphorFix.ini` if you are using SpecialK with MetaphorFix.
