### ISSUE TITLE
Pause menu labels invisible

### ISSUE THREAD

**Issue by scottcollabai** [Lyall/MetaphorFix#41]
Using v0.7.9 on Steam Deck, 800p fullscreen. Shadow res reduced to 1024, but all other settings are default. 

I don't see any of the labels in the pause menu (e.g. "Skill," "Item," "Equipment"). Just the colored backgrounds when selecting an option. Anything I'm missing? 

Note: I haven't tried changing any of the resolution/aspect ratio settings to see if any of those impact this.

**Comment by langiam** [comment]
+1 on this; I also tried to alter various settings in the INI to no avail.

**Comment by Lyall** [comment]
This is a known issue. Offsetting the HUD causes some 3D menu elements to be culled. I added a temporary workaround for ultrawide but it needs a more in-depth solution to fix. If this particular issue is too bothersome, I'd recommend disabling the HUD fix for now and dealing with the minor HUD stretch at 16:10.

**Comment by Logge1002** [comment]
![image](https://github.com/user-attachments/assets/0945af83-3fb4-4607-adb5-7902797f278d)

Same for me. Will try to disable it tomorrow thanks for the advice

**Comment by Lyall** [comment]
Fixed in v0.8.1
