### ISSUE TITLE
Enemies and characters are invisible in battle in the castle dungeon

### ISSUE THREAD

**Issue by SultanSahlabji** [Lyall/MetaphorFix#44]
when initiating combat in the castle dungeon in martira city, the characters and enemies are invisible.

**Comment by Lyall** [comment]
Can you please post your `MetaphorFix.log` file please?

**Comment by SultanSahlabji** [comment]
I think it got overwrote since I downloaded the latest version after I faced the issue, but for what it's worth here's the file, the problem only occurred inside the Kriegante Castle dungeon only, sorry I don't have footage and I think the log file got overwrote. 
[MetaphorFix.log](https://github.com/user-attachments/files/17350967/MetaphorFix.log)

**Comment by Lyall** [comment]
Well that kind of issue should be fixed in v0.7.9, so if you run into it again, let me know.

**Comment by SultanSahlabji** [comment]
alright I will let you know, I disabled the mod during the dungeon and enabled it after the dungeon, but anyway you are doing god's work, thank you so much for your contribution to the ultrawide gang!!

**Comment by Ditsadon** [comment]
> Well that kind of issue should be fixed in v0.7.9, so if you run into it again, let me know.

I'm having the same issue. I just downloaded 0.7.9 yesterday, and all of the characters are invisible after the Heismay awakening cut scene.
This is a fresh log file. I simply stopped playing the game after the bug occurred. I hope this helps! 

[MetaphorFix.log](https://github.com/user-attachments/files/17351637/MetaphorFix.log)

**Comment by TrexCoach** [comment]
I have the same issue too when using v0.7.9. But the problem solved when I set [Fix Hud] option to false.

**Comment by MissPHolic** [comment]
> I have the same issue too when using v0.7.9. But the problem solved when I set [Fix Hud] option to false.

Yes this fixed it for me too, but sadly, the dashing blur is actived again if this setting is set on false.

I don't think this only affects the castle dungeon though, since half of my archetypes are also invisible on the equipment menu. I can see the one equipped by the MC and by the 4th party member (no spoilers but you know who probably), but Strohl and Hulkenberg's are invisible. They appear normally with Fix Hud false too though, so this is a minor problem.

**Comment by Lyall** [comment]
I think this should be fully fixed in v0.8.1.
