### ISSUE TITLE
Menu doesn't display on steam deck - 0.79

### ISSUE THREAD

**Issue by Logge1002** [Lyall/MetaphorFix#45]
On 0.79 the menus are colored but the stylish text is missing (the smaller text is still visible). Steam deck 800p borderless or fullscreen

**Comment by Logge1002** [comment]
![image](https://github.com/user-attachments/assets/7e34baf2-74b1-4aeb-a6cd-a4b121df34ae)

**Comment by Logge1002** [comment]
![image](https://github.com/user-attachments/assets/7e34baf2-74b1-4aeb-a6cd-a4b121df34ae)

**Comment by TheColdOne** [comment]
+1, also seeing this.

I wasn't sure if this was the known issue:
_When using the HUD fix, some menu elements may be culled at <16:9._

But I read that more as being cut off at the edge, not removed entirely.

**Comment by TheColdOne** [comment]
Looks like this was reported already and IS the known issue:

https://github.com/Lyall/MetaphorFix/issues/41
