### ISSUE TITLE
Does not change to 32:9

### ISSUE THREAD

**Issue by trfgm** [Lyall/MetaphorFix#46]
ive extracted the files into the root folder of the game but nothing changes

**Comment by SMCaseyCode** [comment]
Some more info would be nice. Perhaps a screenshot? 32:9 works on my side. Once I extracted I moved the files out of the folder into the game directory.

**Comment by Lyall** [comment]
Yeah more info is necessary. Please upload your `MetaphorFix.log` file if you have one and if you don't then take a screenshot of your game folder contents.

**Comment by trfgm** [comment]
okay so the problem was the file under the code button (sorry im not too savvy with gitgub) which didnt work at all, however the one @ https://github.com/Lyall/MetaphorFix/releases did work
