### ISSUE TITLE
Ultrawide fix disabled in UW monitors results in 21:9 image squished onto 16:9 area

### ISSUE THREAD

**Issue by MeovvCAT** [Lyall/MetaphorFix#5]
Aspect Ratio changes are still applied to 3D rendered space even through the game is constrained to a 16:9 area, resulting in the whole image being squished when fixes are disabled in a UW monitor.

![squish](https://github.com/user-attachments/assets/202ae9b1-5b24-462e-87ea-5900cdb37bbd)

**Comment by Lyall** [comment]
This will be fixed in the next version.

**Comment by Lyall** [comment]
Apologies for the delay, this is fixed in v0.7.3.
