### ISSUE TITLE
Menu misaligned after build 0.8.0_test

### ISSUE THREAD

**Issue by Arachno67** [Lyall/MetaphorFix#55]
Build 0.8.0_test is working great for me (thanks a lot!), since 0.8.0_test2 the menu is misaligned again (my preferred resolution is 4587 x 1920 - NVIDIA DSR):

<img width="958" alt="Metaphor Menu" src="https://github.com/user-attachments/assets/d8d691d6-5b19-43f8-8272-b46e7b5601e0">

**Comment by Arachno67** [comment]
Could you probably keep the temporary solution for 3D menu elements being invisible at ultrawide resolutions as an OPTION, 0.8.0_test worked perfectly well for me ;)

**Comment by Arachno67** [comment]
So this could potentially break things in the 0.8.0 release compared to 0.7.9? If so, I will have to use 0.8.0_test for the time being...

**Comment by Arachno67** [comment]
Hmm, but for me 0.8.0 (release) causes those invisible labels, 0.8.0_test FIXES it. So I was thinking to keep the fix applied in 0.8.0_test as an option, I hope we have no misunderstanding...

**Comment by Ngale29** [comment]
Same issue here using 0.8.0 release

**Comment by blamesoft** [comment]
I didn't have this issue in 0.7.9 but now have it in 0.8.0. I have an ultra wide monitor if that helps and the only value I changed in the .ini are
```
Resolution = 0.5
Volume = 2.0
```

**Comment by Arachno67** [comment]
If you want to use the override for the master volume value I suggest to download “MetaphorFix_v0.8.0_test.zip” from this thread: https://github.com/Lyall/MetaphorFix/issues/22

This is the latest version which fixes the menus with my widescreen configuration, all (test) builds afterwards unfortunately cause those misaligned / invisible labels.

**Comment by Arachno67** [comment]
Fixed in 0.8.1 - again, thanks a lot! 

I am pretty sure ATLUS is not going to fix most of the reported technical issues anytime soon and will never add features like increased draw distance or widescreen support as this would make the PC version too far superior compared to the console versions. 

Your mods are truly essential for PC gaming and very much appreciated!
