### ISSUE TITLE
Does this work with the Microsoft Store version?

### ISSUE THREAD

**Issue by MoTem** [Lyall/MetaphorFix#58]

**Comment by Lyall** [comment]
I don't have the version to test with myself but based on feedback from others it sounds like it should.

**Comment by MoTem** [comment]
Thank you for the response. Is there any guide or instruction on how to do it? As the MS store version has locked down its folder access.

**Comment by MoTem** [comment]
Thank you, I managed to get access and can confirm your mod works on the MS store version of the game. 

This video helped me gain access to the game folder:

https://www.youtube.com/watch?v=hEt86kPa0As
