### ISSUE TITLE
Breaks alt+f4 handler entirely

### ISSUE THREAD

**Issue by SandeMC** [Lyall/MetaphorFix#6]
With `CatchAltF4 = true`, you can't alt+f4 (or end game via menu) at all with this mod

**Comment by Lyall** [comment]
With it set to true, that restores the vanilla game's behaviour. I just removed MetaphorFix to test the vanilla game and now the ALT+F4 handler window thing doesn't even show for me, bizarre. I wonder if it changed in the recent update or if my game is just being dodgy.

**Comment by SandeMC** [comment]
Ah, so this wasn't on the fix then, my bad. Close if you confirm that to not be the case

**Comment by Lyall** [comment]
Well I just restarted my PC, and launching the game without any plugins/mods still doesn't show the exit handler window anymore. It used to show a window asking if you were sure you wanted to exit. Are you able to confirm if this happens on your end @SandeMC? If it does then it's for sure something they broke in the update.

If that is the case, I'll change `CatchAltF4` to `false` by default in the ini.

**Comment by SandeMC** [comment]
> Well I just restarted my PC, and launching the game without any plugins/mods still doesn't show the exit handler window anymore. It used to show a window asking if you were sure you wanted to exit. Are you able to confirm if this happens on your end @SandeMC? If it does then it's for sure something they broke in the update.
> 
> If that is the case, I'll change `CatchAltF4` to `false` by default in the ini to kill the prompt/window.

I've deleted the game already as I was only going to play the demo and remove it but, yeah, that was the case for me too - I had the prompt before installing the mod. Weird shit.

**Comment by SandeMC** [comment]
Wait @Lyall can you test something? Could it be reltaed to the ASI loader?

**Comment by Lyall** [comment]
> Wait @Lyall can you test something? Could it be related to the ASI loader?

I doubt it. I just tested again with no ASI loader in the vanilla game and the exit prompt is still invisible.

**Comment by Lyall** [comment]
That's the option changed to false by default now as of v0.7.3. Perhaps whatever they did in the update for demo broke their exit handler but regardless, it'll be disabled by default now.
