### ISSUE TITLE
MetaphorFix Version 0.7.8 and Up Crashing on Steam Deck with Metaphor Demo

### ISSUE THREAD

**Issue by MattyXarope** [Lyall/MetaphorFix#63]
**System Information:**

- Operating System: SteamOS 3.5.19
- KDE Plasma Version: 5.27.5
- KDE Frameworks Version: 5.107.0
- Qt Version: 5.15.9
- Kernel Version: 6.1.52-valve16-1-neptune-61 (64-bit)
- Graphics Platform: X11
- Processors: 8 × AMD Custom APU 0932
- Memory: 11.5 GiB of RAM
- Graphics Processor: AMD Radeon Graphics
- Manufacturer: Valve
- Product Name: Galileo
- System Version: 1
- Proton Version Used: Proton GE 9-10 (the latest that works with SpecialK)

**What is occurring:**
Using anything above version 0.7.7 does not work with the demo version of Metaphor on Steam Deck. It simply does not load correctly and gets stuck at a black screen right before the intro video normally plays (and this occurs with the "skip intro video" turned on or off - it has no effect). I'm sure that that the process that I'm using to load the mod is correct, as versions 0.7.7 and below work just fine. 

**Other mods used:**
SpecialK

Fix Log:
[MetaphorFix.log](https://github.com/user-attachments/files/17368475/MetaphorFix.log)

**Comment by Cytraen** [comment]
This is probably just a demo thing, as I'm getting this exact same issue on a Windows machine, with or without SpecialK. 0.7.8-0.8.0 lead to a black screen, 0.7.7 works fine.

**Comment by Lyall** [comment]
Yeah this makes sense as the primary thing that changed to accommodate the full game is the intro skip code. You should be able to get around it by disabling the intro skip outright in `MetaphorFix.ini`. 

Unfortunately I can't think of a good way to detect the demo and alter code for it. Both the game and the prologue share the same exe name so I'd have to think of some other way of detecting the demo executable.

**Comment by bmy** [comment]
can confirm that this issue doesn't exist on deck for me when playing the full game

**Comment by MattyXarope** [comment]
I can confirm that using these options in MetaphorFix.ini allows the plugin to load:

```
[Intro Skip]
; Skips intro logos.
Enabled = false
; Set to true to skip the opening movie.
SkipMovie = false
```
A minor inconvenience, but as it stands - these options are broken on the demo version.

**Comment by Lyall** [comment]
I've added a simple method for detecting the demo version and thus restored the prologue demo intro skip in v0.8.2.
