### ISSUE TITLE
No text in pause menu after 0.8.0

### ISSUE THREAD

**Issue by gepti123** [Lyall/MetaphorFix#64]
After i installed version 0.8.0 in pause menu text dissappeared from every option, like equipment, items etc. Im using ultrawide monitor.

**Comment by Hadi10000** [comment]
same here

**Comment by Sephiroth018** [comment]
Same here, looks like this now:
![Screenshot 2024-10-14 234855](https://github.com/user-attachments/assets/add77c22-9a3b-4ac9-ad44-b8c4910bb9ad)

**Comment by ch33s3-alligator** [comment]
This is happening on my machine as well
Running the game on Samsung Odyssey G9 5120 x1440

**Comment by Haruichii** [comment]
I had this issue when using the FIX(0.7.9) combined with TAA mod. Maybe removing the TAA mod (if you use it) would fix the problem.

If you are not using the TAA mod, can you see if using the FIX and setting an ordinary resolution would solve it?

**Comment by Sephiroth018** [comment]
No TAA Mod and it only started with 0.8.0, with 0.7.9 it was/is fine. It has also been reported in [this issue](https://github.com/Lyall/MetaphorFix/issues/55).

**Comment by ch33s3-alligator** [comment]
> This is happening on my machine as well Running the game on Samsung Odyssey G9 5120 x1440

Updated to 0.8.1 and menu text is now visible
Thanks for the update Lyall!

**Comment by Lyall** [comment]
Fixed in v0.8.1
