### ISSUE TITLE
16:10 Hud Elements

### ISSUE THREAD

**Issue by skypanda64** [Lyall/MetaphorFix#69]
16:10 metaphor looks amazing on steamdeck - thanks for the awesome fixes. The latest volume option has also been a game changer with how quiet it was before even on max.

Wondering if there is an easy way to have the hud elements in the right place without stretching them in 16:10.

The stretch is admittedly minor on the small screen but is noticeable if you really pay attention.

**Comment by anthonyrrubio** [comment]
I have the same issue on a laptop with resolution 2560x1600 (also 16:10). It's more noticeable since the size of the screen.
To avoid mispositioning of HUD (especially the mini-map) I have to disable HUD stretched fix in mod config but then the HUD is stretched

**Comment by Lyall** [comment]
This isn't on the cards. Spanning the HUD is very difficult and would require a huge amount of effort. It's already taken a huge amount of work to get the UI to display at 16:9 mostly correctly.

**Comment by skypanda64** [comment]
> This isn't on the cards. Spanning the HUD is very difficult and would require a huge amount of effort. It's already taken a huge amount of work to get the UI to display at 16:9 mostly correctly. 

Good to know. Appreciate the reply and the great work you're doing!!
