### ISSUE TITLE
[Game Window] issue when set to true

### ISSUE THREAD

**Issue by PedSantiago** [Lyall/MetaphorFix#73]
Hi Lyall.

I have an issue on my side whenever I set the Game Window to true.
Whenever I close the game it seems that a process keeps on running and I have to manually shut it down with task manager.
Even though the game is closed, music keeps on playing.

I don't know how much more I can provide here to help but anything I can do to help solve this issue feel free to ask back.

Edit: On a sidenote I noticed this because for some reason setting this to true allowed me to be able to enter the characters name at the start while it being false did not.
Also I am using specialK because of not having true borderless fullscreen (and wanted the game running the audio when tabbed out)

Thanks in advance and also thanks for the other amazing features coming from this fix.

**Comment by Lyall** [comment]
> Hi Lyall.
> 
> I have an issue on my side whenever I set the Game Window to true. Whenever I close the game it seems that a process keeps on running and I have to manually shut it down with task manager. Even though the game is closed, music keeps on playing.
> 
> I don't know how much more I can provide here to help but anything I can do to help solve this issue feel free to ask back.
> 
> Edit: On a sidenote I noticed this because for some reason setting this to true allowed me to be able to enter the characters name at the start while it being false did not. Also I am using specialK because of not having true borderless fullscreen (and wanted the game running the audio when tabbed out)
> 
> Thanks in advance and also thanks for the other amazing features coming from this fix.

You should set the  "[Game Window]" option to false if you are using SpecialK. You don't want both MetaphorFix and SpecialK setting a new WndProc. This is why I added the option, specifically for those using SpecialK.

**Comment by PedSantiago** [comment]
One more question then which is any idea (even if remote) as to why I couldnt type anything during any of the forced keyboard parts?

If nothing at all ill close the issue.

**Comment by Lyall** [comment]
> One more question then which is any idea (even if remote) as to why I couldnt type anything during any of the forced keyboard parts?
> 
> If nothing at all ill close the issue.

Not sure why that would be. I know that SpecialK has a ton of input related settings you can tweak that could have caused that. It could also just have been some bugginess on the game side. I'd just be speculating as to what would have caused that issue for you.

**Comment by PedSantiago** [comment]
That being the case I'm gonna go ahead and say it was game being buggy. 

Many thanks for taking your time answering this. Ill be closing it now then.
