### ISSUE TITLE
Scene visible behind Menu 21:9

### ISSUE THREAD

**Issue by cb613** [Lyall/MetaphorFix#74]
Is it possible to re-add the black bars in the menu? 3440x1440 resolution. Currently, you can see the scene in the background to the left and right of the main Menu. Screenshot shows issue

![2024-10-15](https://github.com/user-attachments/assets/0e97e6d8-485d-4488-918d-5a7ab56bd421)

Interestingly, when entering the main menu, grey bars flash on the left and right momentarily, but then disappear, revealing the scene behind the menu.

**Comment by Lyall** [comment]
Not really feasible I'm afraid. Those grey bars are likely just the background scene from the game switching to a secondary camera view when you open the pause menu. The game actually renders that part the HUD is a secondary camera view, which is part of why it was so hard to fix!

**Comment by cb613** [comment]
> Not really feasible I'm afraid. Those grey bars are likely just the background scene from the game switching to a secondary camera view when you open the pause menu. The game actually renders that part the HUD is a secondary camera view, which is part of why it was so hard to fix!

Understood, that makes sense. Thanks anyway for your work on these fixes, couldn't play ATLUS games without ya!
