### ISSUE TITLE
0.8.2 broken on Windows (ASI fails to load and then auto-deletes itself)

### ISSUE THREAD

**Issue by zandm7** [Lyall/MetaphorFix#78]
See title, release 0.8.2 is broken on Windows.

0.8.1 works fine.

**Comment by MYSTICALMUSICAL** [comment]
If you're using an antivirus, it could be flagging the asi file as a false positive and moving it to quarantine.

**Comment by Sharkcruiser** [comment]
Yeah its not broken for me, works flawlessly

**Comment by Lyall** [comment]
As @MYSTICALMUSICAL said, it's likely being flagged and deleted by Defender. See #68. You'll need to add it as an exception in Defender to stop it from being deleted.

**Comment by zandm7** [comment]
Thanks, adding an exception in Windows Defender fixed it!

I didn't think that was the issue, as normally Defender tells me when it removes a suspicious file, but this time it did not...
