### ISSUE TITLE
Shadow Quality

### ISSUE THREAD

**Issue by AnimeRemover** [Lyall/MetaphorFix#79]
Hi. I have a decent PC with 7900xtx on board. Which Shadow resolution do you recommend for me? I set maximum 16384 and have like 70-100 fps in town, but i guess 16384 is a bit too much and i could save some fps. 

Also, how does customization of lods work? Do lods work at “100” or do objects stop changing lods altogether?

**Comment by system2ckc** [comment]
Set it to 4096, its sharp enough that you won't notice it and the performance impact isn't too bad. 
Draw distance I'm not sure, I just set it to 100 personally, but I never did an A:B test of that.

**Comment by Lyall** [comment]
Yeah 4096 is what I personally use, anything higher tends to be too pin sharp and it also has a noticeable performance hit (especially at higher resolutions). 

As for LOD distance, if you were to set it to 100, it's 10x further than the unmodified game which is going to effectively remove pop-in entirely. It's also not that big of a performance hit for most, as it tends to impact CPU usage more and this game is pretty light on the CPU.  Bear in mind that it doesn't eliminate every kind of pop-in, there are some levels where chunks of the map load in as you move around and those are unaffected by tweaking the LOD distance.
