### ISSUE TITLE
Game crashes when alt-tabbing with PauseFocusLoss=false

### ISSUE THREAD

**Issue by MistressAshai** [Lyall/MetaphorFix#8]
When `PauseOnFocusLoss = false`, alt-tabbing while streaming to Discord causes the game to crash.

**Comment by Lyall** [comment]
I have not been able to replicate this on my end unfortunately. I have however, reworked that part of the fix slightly, so here is a test build that might fix the issue for you. 

[MetaphorFix_v0.7.7_test.zip](https://github.com/user-attachments/files/17278337/MetaphorFix_v0.7.7_test.zip)

**Comment by MistressAshai** [comment]
That didn't fix it unfortunately. Additionally it seems like it just crashes upon alt tabbing in general.

Here's the log, but I don't think there's anything noteworthy.
[MetaphorFix.log](https://github.com/user-attachments/files/17278966/MetaphorFix.log)

**Comment by Lyall** [comment]
This option was removed in v0.7.7
