### ISSUE TITLE
Bring back PauseFocusLoss=false?

### ISSUE THREAD

**Issue by IAmRythian** [Lyall/MetaphorFix#82]
I quite enjoyed this setting back before it was removed, and didn't suffer from any crashes myself (despite alt-tabbing a lot). Is there a chance this can be put back in, perhaps with a warning in the .ini file that some people (one person?) have experienced crashes with it?

More of a wish or suggestion rather than an issue really, so sorry if this is in the wrong place.

**Comment by Foul-Tarnished** [comment]
I just use "Continue Rendering" feature in SpecialK

**Comment by misterwiggle** [comment]
> I just use "Continue Rendering" feature in SpecialK

are you using steam? cuz mine on ms store version won't launch with specialK

**Comment by IAmRythian** [comment]
Thank you!
