### ISSUE TITLE
[Bug] Camera Shake fix broken in new patch

### ISSUE THREAD

**Issue by solidsoap23** [Lyall/MetaphorFix#91]
The fix to the camera shake during dialogues seems to have been broken with the patch that came out on the 18th of October.

**Comment by system2ckc** [comment]
I think the new behavior for non-modded camera shake toggle is when you disable it, it will still apply in combat and in B-tier dialog scenes. In the 21:9 cutscenes there will be no camera shake.

**Comment by MakoEyes** [comment]
Yep. Camera shake setting is now broken sadly.

**Comment by Randy28CR** [comment]
True. I hope our GOAT @Lyall  fixes this back. 
I just hate that sway stuff. 
Hopefully it can be adjusted to be disable once again

**Comment by Randy28CR** [comment]
Thank you mate!

**Comment by system2ckc** [comment]
Updated version does seem to work but I have to actually ENABLE it in game, and then set Disable Camera Shake = True in the ini file.

**Comment by system2ckc** [comment]
> I'll look at overriding it in the next version, should be do-able. It would probably make more sense if it just forces it off without any further user interaction.
> 
> Edit: Actually now that I'm testing this option, camera shake is being forced off regardless of whether I launch the game with "Camera Shake" on or off. Are you using the MS Store version of the game @system2ckc? I saw mention in another issue of the updated pattern scan not working in that version.

I'm on the steam version. But, I retested it and it actually seems to be working fine now on all four camera shake scenarios regardless of in-game Camera Shake Option. I think when I tested last time it may have been caused by the area I was testing in, its somewhat of a special case area so that might have been it. Sorry for the confusion.
