### ISSUE TITLE
[Feature Request] let us multiply the Anti Aliasing if possible

### ISSUE THREAD

**Issue by McMarius11** [Lyall/MetaphorFix#93]
They added the option of SMAA but is it possible to add the value like 4x SMAA?

**Comment by Lyall** [comment]
That's not possible. SMAA is a post process anti-aliasing technique, and despite having a similar name to MSAA, it's not sample-based and you can't increase it's quality in that way.

If you're looking for better AA techniques, I'd recommend employing DSR/VSR for downsampling. There also some ReShade presets on NexusMods for applying different methods of anti-aliasing, though your mileage may vary with their effectiveness.
